// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zakázky;

#nullable disable

namespace Zakázky.Migrations
{
    [DbContext(typeof(MainDBContext))]
    [Migration("20250421171952_M210420251919")]
    partial class M210420251919
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zakázky.DB_Class.AdressList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("SubjectID");

                    b.ToTable("AdressList");
                });

            modelBuilder.Entity("Zakázky.DB_Class.BindingSubjectToAdress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AdressId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BindingSubjectToAdress");
                });

            modelBuilder.Entity("Zakázky.DB_Class.BindingSubjectToContact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BindingSubjectToContact");
                });

            modelBuilder.Entity("Zakázky.DB_Class.ContactList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Phone")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("ContactList");
                });

            modelBuilder.Entity("Zakázky.DB_Class.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Zakázky.DB_Class.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ContractorID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustumerID")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeTookOverID")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedTotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderItemID")
                        .HasColumnType("int");

                    b.Property<string>("OrderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("orderState")
                        .HasColumnType("int");

                    b.Property<int>("orderType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ContractorID");

                    b.HasIndex("CustumerID");

                    b.HasIndex("EmployeeTookOverID");

                    b.HasIndex("OrderItemID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Zakázky.DB_Class.OrderItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OrderItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderItemNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderItemQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Zakázky.DB_Class.Subject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AdressListID")
                        .HasColumnType("int");

                    b.Property<int?>("ContactListID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ICO")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AdressListID");

                    b.HasIndex("ContactListID");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("Zakázky.DB_Class.AdressList", b =>
                {
                    b.HasOne("Zakázky.DB_Class.Subject", null)
                        .WithMany("AdressList")
                        .HasForeignKey("SubjectID");
                });

            modelBuilder.Entity("Zakázky.DB_Class.Employee", b =>
                {
                    b.HasOne("Zakázky.DB_Class.ContactList", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Zakázky.DB_Class.Order", b =>
                {
                    b.HasOne("Zakázky.DB_Class.Subject", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorID");

                    b.HasOne("Zakázky.DB_Class.Subject", "Custumer")
                        .WithMany()
                        .HasForeignKey("CustumerID");

                    b.HasOne("Zakázky.DB_Class.Employee", "EmployeeTookOver")
                        .WithMany()
                        .HasForeignKey("EmployeeTookOverID");

                    b.HasOne("Zakázky.DB_Class.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemID");

                    b.Navigation("Contractor");

                    b.Navigation("Custumer");

                    b.Navigation("EmployeeTookOver");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Zakázky.DB_Class.Subject", b =>
                {
                    b.HasOne("Zakázky.DB_Class.AdressList", "Adress")
                        .WithMany()
                        .HasForeignKey("AdressListID");

                    b.HasOne("Zakázky.DB_Class.ContactList", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactListID");

                    b.Navigation("Adress");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Zakázky.DB_Class.Subject", b =>
                {
                    b.Navigation("AdressList");
                });
#pragma warning restore 612, 618
        }
    }
}
